/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/material/verbose 0
/run/particle/verbose 0
/janus/det/setWorldMaterial G4_Galactic
/janus/det/setChamberMaterial G4_AIR
/janus/det/setTargetShape Cylinder
/janus/det/setTargetMaterial G4_W
/janus/det/setTargetWidth 10 cm
/janus/det/setTargetPosition 0 0 0 cm
/janus/output/setFilter 0
/janus/output/setLightFilter 1
/run/numberOfThreads 12
/run/initialize
/janus/tracking/saveSecondaries true
/janus/tracking/recordMode Birth
/gun/particle proton
/gun/beam/profile Gaussian
/gun/beam/sigma 1 cm
/gun/beam/direction 0 0 1
/gun/beam/offset 0 0 -10 cm
/gun/beam/energyDist Mono
/gun/beam/energyMean 26 GeV
/run/beamOn 100