/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/material/verbose 0
/run/particle/verbose 0
/janus/det/setWorldMaterial G4_Galactic
/janus/det/setChamberMaterial G4_AIR
/janus/det/setChamberWidth 40.0 cm
/janus/det/setChamberLength 120.0 cm
/janus/det/setTargetShape Cylinder
/janus/det/setTargetMaterial G4_Ir
/janus/det/setTargetWidth 3.0 mm
/janus/det/setTargetLength 55 mm
/janus/det/setTargetPosition 0 0 +25.0 cm
/janus/output/setFilter 0
/janus/output/setLightFilter 1
/run/numberOfThreads 12
/run/initialize
/janus/tracking/saveSecondaries true
/janus/tracking/recordMode Hit
/gun/particle proton
/gun/beam/profile Gaussian
/gun/beam/sigma 0.5 mm
/gun/beam/direction 0 0 1
/gun/beam/offset 0 0 0 cm
/gun/beam/energyDist Mono
/gun/beam/energyMean 26 GeV
/vis/open OGL
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 100
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 1
/vis/modeling/trajectories/drawByParticleID-0/set e+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set anti_proton red
/vis/modeling/trajectories/drawByParticleID-0/set proton blue
/vis/modeling/trajectories/drawByParticleID-0/set e- cyan
/vis/modeling/trajectories/drawByParticleID-0/set gamma gray
/vis/modeling/trajectories/drawByParticleID-0/set neutron green
/vis/modeling/trajectories/drawByParticleID-0/set pi+ yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi- yellow
/vis/modeling/trajectories/drawByParticleID-0/set pi0 white
/vis/scene/endOfEventAction accumulate 1000
/vis/set/textColour green
/vis/set/textLayout right
/vis/scene/add/text2D 0.9 -.9 24 ! ! Janus
/vis/set/textLayout
/vis/set/textColour
/vis/scene/add/eventID
/vis/geometry/set/visibility World 0 false
/vis/geometry/set/colour Chamber 1 1 1 1 0.1
/vis/geometry/set/colour Target 0.8 0.8 0.8 1.0
/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150
/gui/addMenu run Run
/gui/addButton run "Run 1 event" "/run/beamOn 1"
/gui/addButton run "Run 10 events" "/run/beamOn 10"
/gui/addButton run "Run 100 events" "/run/beamOn 100"
/gui/addButton run "Run 1000 events" "/run/beamOn 1000"
/gui/addButton run "Run Configured Beam (10000)" "/run/beamOn 10000"
/gui/addButton run "Clear Screen" "/vis/viewer/clear"
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
/vis/viewer/flush