/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/process/verbose 0
/material/verbose 0
/run/particle/verbose 0
/janus/det/setWorldMaterial G4_Galactic
/janus/det/setChamberMaterial G4_AIR
/janus/det/setChamberWidth 40.0 cm
/janus/det/setChamberLength 120.0 cm
/janus/det/setTargetShape Cylinder
/janus/det/setTargetMaterial G4_Ir
/janus/det/setTargetWidth 3.0 mm
/janus/det/setTargetLength 55 mm
/janus/det/setTargetPosition 0 0 -27.5 cm
/janus/output/setFilter 0
/janus/output/setLightFilter 0
/run/numberOfThreads 12
/run/initialize
/janus/tracking/saveSecondaries true
/janus/tracking/recordMode Hit
/gun/particle proton
/gun/beam/profile Gaussian
/gun/beam/sigma 0.5 mm
/gun/beam/direction 0 0 1
/gun/beam/offset 0 0 0 cm
/gun/beam/energyDist Mono
/gun/beam/energyMean 26 GeV
/run/beamOn 10000